In [ ]:
# Exercise 1: Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [5]:
import numpy as np

In [7]:
array_1 = np.array([1,2,3,4,5,6,7,8,9,10])
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
type(array_1)

numpy.ndarray

In [23]:
array_2 = array_1.reshape(2,5)
array_2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
# Exercise 2: Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index

In [63]:
array_3 = np.arange(0,21)
array_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [67]:
array_4 = array_3[5:16]
array_4

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [69]:
# Exercise 3: Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value

In [3]:
import pandas as pd

In [7]:
series_1 = pd.Series(['apples','bananas','oranges'], index= [1,2,3])
series_1

1     apples
2    bananas
3    oranges
dtype: object

In [17]:
series_1 = pd.Series(['apples','bananas','oranges'], index= [1,2,3])
series_1[4] = 'pears'
series_1

1     apples
2    bananas
3    oranges
4      pears
dtype: object